services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-studs
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - BLSS-labs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "v.amuz@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1488"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "6980:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - BLSS-labs

  camunda-postgres:
    image: postgres:15-alpine
    container_name: camunda-postgres
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda123
    ports:
      - "5433:5432"
    volumes:
      - camunda_postgres_data:/var/lib/postgresql/data
    networks:
      - BLSS-labs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camunda -d camunda"]
      interval: 10s
      timeout: 5s
      retries: 5

  camunda:
    image: camunda/camunda-bpm-platform:7.20.0
    container_name: camunda
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://camunda-postgres:5432/camunda
      DB_USERNAME: camunda
      DB_PASSWORD: camunda123
      WAIT_FOR: camunda-postgres:5432
      CAMUNDA_BPM_ADMIN_USER_ID: admin
      CAMUNDA_BPM_ADMIN_USER_PASSWORD: admin123
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    depends_on:
      camunda-postgres:
        condition: service_healthy
    networks:
      - BLSS-labs
    volumes:
      - camunda_data:/camunda

volumes:
  postgres_data:
  pgadmin_data:
  camunda_postgres_data:
  camunda_data:

networks:
  BLSS-labs:
    driver: bridge
