@baseUrl = http://localhost:8080
@productId = {{productId1}}
@productId2 = {{productId2}}

### Create product
POST {{baseUrl}}/inventory/products
Content-Type: application/json

{
  "name": "Laptop Pro 1511",
  "price": 213789217871283721893182309821093892189,  // TODO НЕТ ОГРАНИЧЕНИЯ ПО ЦЕНЕ ВВЕРХ
  "initialCount": 250 // TODO 10 млн
}

> {% if (response.status >= 200 && response.status < 300 && response.body?.data?.product?.id) { client.global.set("productId1", response.body.data.product.id); } %}

### Create product
POST {{baseUrl}}/inventory/products
Content-Type: application/json

{
  "name": "Smartphone X",
  "price": 69990.00,
  "initialCount": 500
}

> {% if (response.status >= 200 && response.status < 300 && response.body?.data?.product?.id) { client.global.set("productId2", response.body.data.product.id); } %}

### Create product
POST {{baseUrl}}/inventory/products
Content-Type: application/json

{
  "name": "Wireless Headphones",
  "price": 12990.00,
  "initialCount": 1200
}

### Update product
PUT {{baseUrl}}/inventory/products/{{productId}}
Content-Type: application/json

{
  "name": "Laptop Pro 15",
  "price": 169990.00
}

### Update product count
PATCH {{baseUrl}}/inventory/products/{{productId}}/count?change=59898989080890899908

### Get product
GET {{baseUrl}}/inventory/products/{{productId}}

### Get all products
GET {{baseUrl}}/inventory/products

### Get product count
GET {{baseUrl}}/inventory/products/{{productId}}/count
