@baseUrl = http://localhost:8080
@orderId = 00000000-0000-0000-0000-000000000010
@ownerId = {{ownerId}}
@locationId = {{locationId}}
@productId1 = {{productId1}}
@productId2 = {{productId2}}

### Create order
POST {{baseUrl}}/order/create
Content-Type: application/json

{
  "owner": "{{ownerId}}",
  "location": "{{locationId}}",
  "productIds": [
    "{{productId1}}",
    "{{productId2}}"
  ]
}

> {% if (response.status === 201) { client.global.set("orderId", response.body.orderId); } %}

### Get order by id
GET {{baseUrl}}/order/{{orderId}}

> {% if (response.status === 200 && response.body.positions?.length) { client.global.set("orderItemId", response.body.positions[0].id); } %}

### Update order status
PATCH {{baseUrl}}/order/{{orderId}}/status?status=PROCESSING
