@baseUrl = http://localhost:8080
@orderId = 663e7e2b-ba24-4e32-bdf6-7119f5bd08f2
@orderItemId = 27a7364c-4ec4-46fd-a0f3-4ae86b55d23a
@orderItemId1 = 7941bc5c-271d-43d8-b284-4a01715eda4b

### NOTE: orderId must exist. If missing, set @orderId manually.

### Get order and capture itemId
GET {{baseUrl}}/order/{{orderId}}

> {% if (response.status === 200 && response.body?.data?.positions?.length) { client.global.set("orderItemId", response.body.data.positions[0].id); } %}

### Mark order item as delivered
POST {{baseUrl}}/mark-delivered
Content-Type: application/json

{
  "itemId": "{{orderItemId1}}",
  "yacheyka": "A-12-2"
}

### Next order status
PATCH {{baseUrl}}/order/{{orderId}}/status/next
