@baseUrl = http://localhost:8080

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "test@a.a"
}

> {% if (response.status >= 200 && response.status < 300 && response.body?.data?.id) { client.global.set("ownerId", response.body.data.id); } %}
