spring:
  application:
    name: status-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s408145}
    password: ${SPRING_DATASOURCE_PASSWORD:JLzD%6772}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  artemis:
    mode: native
    broker-url: ${SPRING_JMS_ARTEMIS_BROKER_URL:tcp://localhost:61616}
    user: ${SPRING_JMS_ARTEMIS_USER:artemis}
    password: ${SPRING_JMS_ARTEMIS_PASSWORD:artemis}

server:
  port: ${SERVER_PORT:25105}

# JMS queue names
jms:
  queue:
    order-status-changed: order.status.changed
    notifications: status.notifications

# Service URLs
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:25104}
order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:25103}
