spring:
  application:
    name: status-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:studs}
    username: ${POSTGRES_USER:s408145}
    password: ${POSTGRES_PASSWORD:JLzD%6772}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  artemis:
    mode: native
    broker-url: ${ARTEMIS_BROKER_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USER:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}

server:
  port: 25105

security:
  users:
    xml-path: ${SECURITY_USERS_XML_PATH:./users.xml}

# JMS queue names
jms:
  queue:
    order-status-changed: order.status.changed
    notifications: status.notifications

# Service URLs
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:25104}
order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:25103}
