spring.application.name: blss

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s408145
    password: JLzD%6772
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
