spring:
  application:
    name: blss
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:studs}
    username: ${POSTGRES_USER:s408145}
    password: ${POSTGRES_PASSWORD:JLzD%6772}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: ${SPRING_PORT:25102}

security:
  users:
    xml-path: ${SECURITY_USERS_XML_PATH:./users.xml}


